BEGIN;

CREATE TABLE IF NOT EXISTS users(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(84) NOT NULL,
    email VARCHAR(124) NOT NULL UNIQUE,
    password TEXT NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products(
    id SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS carts(
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users (id),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- JUNCTION TABLE
CREATE TABLE IF NOT EXISTS cart_item(
    id SERIAL PRIMARY KEY,
    quantity INTEGER DEFAULT 1,
    cart_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    
    FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,

    UNIQUE (cart_id, product_id),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS checkouts(
    id SERIAL PRIMARY KEY,
    cart_id INTEGER NOT NULL,
    
    FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;